apiVersion: v1
kind: Service
metadata:
  name: "whisk-kafka-service"
spec:
  selector:
    name: whisk
    type: kafka
  ports:
    - port: 2181
      targetPort: 2181
      name: zookeeper
    - port: 9092
      targetPort: 9092
      name: kafka
