apiVersion: v1
kind: Service
metadata:
  name: "whisk-edge-service"
spec:
  selector:
    name: whisk
    type: edge
  ports:
  - port: 80
    targetPort: 80
    name: nginx
  - port: 443
    targetPort: 443
    name: nginx-1
  - port: 8443
    targetPort: 8443
    name: nginx-2
