apiVersion: v1
kind: Service
metadata:
  name: "whisk-controllers-service"
spec:
  selector:
    name: whisk
    type: controllers
  ports:
    - port: 10001
      targetPort: 8080
      name: controller
