---
# Install the API Gateway route management actions.
- name: install route management actions
  shell: ./installRouteMgmt.sh {{ catalog_auth_key }} {{ kubeips.edge.pod_ip }} {{ catalog_namespace }} {{ cli_path }} {{ db_apigw_username }} {{ db_apigw_password }} chdir="{{ openwhisk_home }}/ansible/roles/routemgmt/files"
  environment:
    OPENWHISK_HOME: "{{ openwhisk_home }}"
